# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      # Check-out repository
      - uses: actions/checkout@v3

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x' 
          architecture: 'x64'
      
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .


      - uses: actions/upload-artifact@v2
        with:
          name: main
          path: dist/windows
